name: Python License Check

on:
  pull_request:
    paths:
    - 'common/python/**'
  workflow_dispatch:

jobs:
  python-license-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: License Check
        run: |
          set -ex
          source setupenv.sh
          python3 -m pip install liccheck
          for f in $(find -type f -name "requirements.txt"); do
            python3 -m pip install -r $f
            liccheck -s .github/.license_check.ini -r $f
          done
